QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7735_spi
QUANTUM_PAINTER_DRIVERS += rgb565_surface

QUANTUM_PAINTER_SUPPORTS_256_PALETTE = yes
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

RAW_ENABLE = yes
CONSOLE_ENABLE = yes
PROGRAMMABLE_BUTTON_ENABLE = yes
LEADER_ENABLE = yes
